SELECT CUSTOMERID,
FIRSTNAME,
LASTNAME,
(ISNULL(FIRSTNAME,'')+' '+ISNULL(LastName,'')) AS FULLNAME,
SCORE,
ISNULL(SCORE,0)+10 AS SCOREWITHBONOUS
FROM Sales.Customers


/* THIS SI USED TO CONNECT TO TABLE WITHTTHE KEYS WITH NULL VAUE*/

/*THE NULL FUCTION IS ALSO USED TO SORT THE VALE*/

/* FOR EXAMPLE I WANT TO SORT BY SCORE IN LOWEST TO HIGHEST BUT SHOW THE NULL AT LAST*/

SELECT CUSTOMERID,
Score
FROM Sales.Customers
ORDER BY CASE WHEN SCORE IS NULL THEN 1 ELSE 0 END,Score